vich_uploader:
    db_driver: orm

    mappings:
        posts:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: App\Service\FileNamer
        avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: App\Service\FileNamer
